apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-01-11T12:07:38Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    k8s-app: kube-crpd-worker
  name: conf-kube-crpd-worker-sts-1
  namespace: jcnr
  uid: 7347600a-82a4-49f2-979d-f909eb82938c
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: jcnrstorage
  volumeMode: Filesystem
  volumeName: jcnr-pv-volume-2
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 256Mi
  phase: Bound
