apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-11T12:07:38Z"
  generateName: kube-crpd-worker-sts-
  labels:
    apps.kubernetes.io/pod-index: "0"
    controller-revision-hash: kube-crpd-worker-sts-77c8846d57
    k8s-app: kube-crpd-worker
    statefulset.kubernetes.io/pod-name: kube-crpd-worker-sts-0
  name: kube-crpd-worker-sts-0
  namespace: jcnr
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: kube-crpd-worker-sts
    uid: 2fbf261d-fa78-4513-b195-3631c9001f61
  uid: e3b3854c-bab5-423e-9098-b414806a72fa
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: k8s-app
            operator: In
            values:
            - kube-crpd-worker
        topologyKey: kubernetes.io/hostname
  containers:
  - args:
    - /config/scripts/jcnr-pre-init.sh && exec /sbin/runit-init.sh
    command:
    - /bin/sh
    - -c
    env:
    - name: NODE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: CRPD_PERSONALITY
      value: jcnr
    - name: IS_MASTER
      value: "False"
    - name: SYSLOG_REMOTE_DEST
      value: '@127.0.0.1:50055'
    - name: VROUTER_GRPC_PORT
    image: svl-artifactory.juniper.net/junos-docker-local/warthog/amd64/crpd:23.4R1.9
    imagePullPolicy: IfNotPresent
    lifecycle:
      postStart:
        exec:
          command:
          - /bin/sh
          - -c
          - /config/scripts/jcnr-post-init.sh
    livenessProbe:
      exec:
        command:
        - /config/scripts/health-check.sh
        - --liveness
        - --vrouter
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: kube-crpd-worker
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_ADMIN
      privileged: true
    startupProbe:
      exec:
        command:
        - /config/scripts/health-check.sh
        - --startup
        - --vrouter
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /config
      name: conf
    - mountPath: /host
      name: cni
    - mountPath: /etc/secrets
      name: secrets
    - mountPath: /var/run
      name: var-run
    - mountPath: /var/log
      name: var-log
    - mountPath: /etc/localtime
      name: host-time
    - mountPath: /var/crash
      name: crash
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dmth6
      readOnly: true
  - command:
    - /telemetry-exporter
    - run
    - -c
    - /etc/telemetry-exporter/config/config-crpd.yaml,/etc/telemetry-exporter/config-overlay/config-crpd.yaml
    env:
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: TYPE
      value: crpd
    - name: NAMESPACE
      value: jcnr
    image: 10.108.30.13:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-telemetry-exporter:master
    imagePullPolicy: IfNotPresent
    name: jcnr-crpd-telemetry-exporter
    ports:
    - containerPort: 8072
      hostPort: 8072
      name: metrics
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /testing
      name: telemetry-exporter-overrides
    - mountPath: /etc/telemetry-exporter/config-overlay
      name: crpd-telemetry-exporter-config
    - mountPath: /etc/secrets
      name: secrets
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dmth6
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  hostname: kube-crpd-worker-sts-0
  initContainers:
  - args:
    - -c
    - python3 -u crpdconfig_generator/crpdconfig_generator.py
    command:
    - /bin/sh
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: PYTHONUNBUFFERED
      value: "1"
    image: svl-artifactory.juniper.net/junos-docker-local/warthog/amd64/crpdconfig-generator:v21
    imagePullPolicy: IfNotPresent
    name: jcnr-crpd-config
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/jcnr-config
      name: jcnr-config
    - mountPath: /opt/jcnr-custom-config
      name: jcnr-custom-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dmth6
      readOnly: true
  - env:
    - name: NODE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: CRPD_PERSONALITY
      value: jcnr
    - name: CRPD_CONFIG_DIR
      value: /config
    - name: IS_MASTER
      value: "False"
    - name: CRPD_CONFIG_TEMPLATE
      value: /etc/jcnr/crpdconfig
    - name: PRIMARY_CNI
      value: "False"
    - name: BGP_CONNECT_PORT
      value: "179"
    - name: BGP_LISTEN_PORT
      value: "178"
    - name: SRGB_START_LABEL
      value: "400000"
    - name: SRGB_INDEX_RANGE
      value: "4000"
    - name: SYSLOG_REMOTE_DEST
      value: '@127.0.0.1:50055'
    - name: CNI_LOG_FILE_SIZE
      value: "1"
    - name: CNI_LOG_FILE_COUNT
      value: "10"
    - name: CORE_PATTERN
    - name: CNI_LOG_PATH
      value: /var/log/jcnr/
    - name: CNI_LOG_LEVEL
      value: info
    image: svl-artifactory.juniper.net/junos-docker-local/warthog/amd64/jcnr-cni:master-20231228-97ba7a8
    imagePullPolicy: IfNotPresent
    name: install-cni
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_ADMIN
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /config
      name: conf
    - mountPath: /host
      name: cni
    - mountPath: /etc/jcnr
      name: jcnr-config-generated
    - mountPath: /etc/jcnr-params
      name: jcnr-params
    - mountPath: /etc/secrets
      name: secrets
    - mountPath: /var/run
      name: var-run
    - mountPath: /etc/localtime
      name: host-time
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dmth6
      readOnly: true
  nodeName: trohit-k8s-dpdk-kubelet1-1k3tt0.englab.juniper.net
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: crpd
  serviceAccountName: crpd
  subdomain: jcnr
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: conf
    persistentVolumeClaim:
      claimName: conf-kube-crpd-worker-sts-0
  - hostPath:
      path: /
      type: ""
    name: cni
  - configMap:
      defaultMode: 420
      name: jcnr-config
    name: jcnr-config
  - configMap:
      defaultMode: 420
      name: jcnr-custom-config
    name: jcnr-custom-config
  - configMap:
      defaultMode: 420
      name: jcnr-config-generated
    name: jcnr-config-generated
  - configMap:
      defaultMode: 420
      name: jcnr-params
      optional: true
    name: jcnr-params
  - name: secrets
    secret:
      defaultMode: 420
      secretName: jcnr-secrets
  - hostPath:
      path: /var/run/crpd/
      type: ""
    name: var-run
  - hostPath:
      path: /var/log/jcnr/
      type: ""
    name: var-log
  - hostPath:
      path: /etc/localtime
      type: ""
    name: host-time
  - hostPath:
      path: /var/crash
      type: ""
    name: crash
  - configMap:
      defaultMode: 420
      name: crpd-telemetry-exporter-config
    name: crpd-telemetry-exporter-config
  - configMap:
      defaultMode: 420
      name: telemetry-exporter-overrides-configmap
      optional: true
    name: telemetry-exporter-overrides
  - name: kube-api-access-dmth6
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:07:56Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:08:30Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:08:30Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:07:39Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://07831d1d59d6b06063a101e3155bae7f528d2697e4d91575fa2a1e010e5c0aac
    image: 10.108.30.13:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-telemetry-exporter:master
    imageID: 4f93c0954d18da04c11dd5700666ce2a49613190d8449e4dcefa5f781c2437b4
    lastState: {}
    name: jcnr-crpd-telemetry-exporter
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-11T12:08:18Z"
  - containerID: cri-o://e178a33bf0d03980e1ffd912b5fdea7648d8a121d6826fe6b523eecf158eeaff
    image: svl-artifactory.juniper.net/junos-docker-local/warthog/amd64/crpd:23.4R1.9
    imageID: 9ed2949df81f85f5411f151abd9b7fb6ec334fb986638404ef0822f4079c5318
    lastState: {}
    name: kube-crpd-worker
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-11T12:08:07Z"
  hostIP: 192.168.1.3
  initContainerStatuses:
  - containerID: cri-o://ea0fe6ac1a0c5df32505b3d09f0a9499723960ef7e59e5eed8031f7097b21f4d
    image: svl-artifactory.juniper.net/junos-docker-local/warthog/amd64/crpdconfig-generator:v21
    imageID: b0804dda66d833cb2e4b2847807b0ccb1ec1f87c467c20e9779bbc3f088c493b
    lastState: {}
    name: jcnr-crpd-config
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://ea0fe6ac1a0c5df32505b3d09f0a9499723960ef7e59e5eed8031f7097b21f4d
        exitCode: 0
        finishedAt: "2024-01-11T12:07:50Z"
        reason: Completed
        startedAt: "2024-01-11T12:07:44Z"
  - containerID: cri-o://945c68625e66d7cd73871423f81025107a8a451b8b8fe85edc42e02fec635bfe
    image: svl-artifactory.juniper.net/junos-docker-local/warthog/amd64/jcnr-cni:master-20231228-97ba7a8
    imageID: 669142a1d7d3b44e9444755baa9637b2604b026fd1ace46d39cdc9f0a4fae260
    lastState: {}
    name: install-cni
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://945c68625e66d7cd73871423f81025107a8a451b8b8fe85edc42e02fec635bfe
        exitCode: 0
        finishedAt: "2024-01-11T12:07:56Z"
        reason: Completed
        startedAt: "2024-01-11T12:07:56Z"
  phase: Running
  podIP: 192.168.1.3
  podIPs:
  - ip: 192.168.1.3
  qosClass: BestEffort
  startTime: "2024-01-11T12:07:39Z"
