apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-11T12:07:38Z"
  generateName: syslog-ng-
  labels:
    app.kubernetes.io/name: syslog-ng
    controller-revision-hash: 549d4b96c
    pod-template-generation: "1"
  name: syslog-ng-54slf
  namespace: jcnr
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: syslog-ng
    uid: 1cf4d560-86cc-43c2-a242-b0c40a39fbfa
  uid: 69857d69-5619-4556-a536-80d446af8097
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - trohit-k8s-master-1k3tt0.englab.juniper.net
  containers:
  - command:
    - sh
    - -c
    - HOSTUPTIME=$(cut -d'.' -f1 /proc/uptime) /usr/sbin/syslog-ng -F -f /config/syslog-ng.conf
      --persist-file /config/syslog-ng.persist --pidfile=/config/syslog-ng.pid --control=/config/syslog-ng.ctl
      --stderr --no-caps
    env:
    - name: CONTRAIL_VROUTER_LOG_PATH
      value: /var/log/jcnr/
    image: svl-artifactory.juniper.net/contrail-docker/x86_64/syslog-ng:v6
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - syslog-ng-ctl
        - stats
        - --control=config/syslog-ng.ctl
      failureThreshold: 5
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    name: syslog-ng
    ports:
    - containerPort: 6601
      hostPort: 6601
      name: syslog-tcp
      protocol: TCP
    - containerPort: 5514
      hostPort: 5514
      name: syslog-udp
      protocol: UDP
    resources: {}
    securityContext:
      privileged: true
      runAsUser: 0
    startupProbe:
      exec:
        command:
        - syslog-ng-ctl
        - stats
        - --control=config/syslog-ng.ctl
      failureThreshold: 5
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /config/syslog-ng.conf
      name: config
      subPath: syslog-ng.conf
    - mountPath: /var/log/jcnr/
      name: contraillogs
    - mountPath: /var/log/jcnr_notifications.json
      name: jcnrnotifications
    - mountPath: /etc/localtime
      name: host-time
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-d8t5b
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: trohit-k8s-master-1k3tt0.englab.juniper.net
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 2000
    runAsGroup: 3000
    runAsUser: 1000
  serviceAccount: crpd
  serviceAccountName: crpd
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - configMap:
      defaultMode: 420
      name: syslog-config
    name: config
  - hostPath:
      path: /var/log/jcnr/
      type: ""
    name: contraillogs
  - hostPath:
      path: /var/log/jcnr/jcnr_notifications.json
      type: FileOrCreate
    name: jcnrnotifications
  - hostPath:
      path: /etc/localtime
      type: ""
    name: host-time
  - name: kube-api-access-d8t5b
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:07:38Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:08:09Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:08:09Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:07:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://b01122d3a313ad949a8b4c154a9fa7dc6bc710080e944619cab7facc1533bbe6
    image: svl-artifactory.juniper.net/contrail-docker/x86_64/syslog-ng:v6
    imageID: 58b90805f1f13662432e3f639ce1670118e1ff653283cac5468807ec44782049
    lastState: {}
    name: syslog-ng
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-11T12:08:02Z"
  hostIP: 192.168.1.2
  phase: Running
  podIP: 192.168.1.2
  podIPs:
  - ip: 192.168.1.2
  qosClass: BestEffort
  startTime: "2024-01-11T12:07:38Z"
