apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-11T12:07:38Z"
  generateName: contrail-k8s-deployer-7f6f88bb47-
  labels:
    app: contrail-k8s-deployer
    pod-template-hash: 7f6f88bb47
  name: contrail-k8s-deployer-7f6f88bb47-nr6k9
  namespace: contrail-deploy
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: contrail-k8s-deployer-7f6f88bb47
    uid: 6642f4e3-c685-4d1c-b925-4e4499283387
  uid: c7d1115b-1ef0-415a-afec-5600e33d271e
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
  containers:
  - command:
    - sh
    - -c
    - /manager --metrics-addr 127.0.0.1:8081 --headless-mode true
    image: 10.108.30.13:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-k8s-deployer:master
    imagePullPolicy: IfNotPresent
    name: contrail-k8s-deployer
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/localtime
      name: host-time
    - mountPath: /tmp/k8s-webhook-server/serving-certs
      name: cert
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rkmsf
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  initContainers:
  - command:
    - kubectl
    - apply
    - --server-side=true
    - --force-conflicts
    - -k
    - /distributed-crd
    image: 10.108.30.13:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-k8s-distributed-crdloader:master
    imagePullPolicy: IfNotPresent
    name: contrail-k8s-crdloader
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/localtime
      name: host-time
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rkmsf
      readOnly: true
  nodeName: trohit-k8s-dpdk-kubelet1-1k3tt0.englab.juniper.net
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: contrail-deploy-serviceaccount
  serviceAccountName: contrail-deploy-serviceaccount
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/localtime
      type: ""
    name: host-time
  - name: cert
    secret:
      defaultMode: 420
      secretName: webhook-server-cert
  - name: kube-api-access-rkmsf
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:07:44Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:07:46Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:07:46Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:07:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://d8d620378d95921cc1fc70e089d91ebaac284561bfb1ec114f9232d8218516b1
    image: 10.108.30.13:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-k8s-deployer:master
    imageID: 42533fc6e295118e6d78833ac56efc0b911b4fc981c502313b80faded4d8ee52
    lastState: {}
    name: contrail-k8s-deployer
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-11T12:07:46Z"
  hostIP: 192.168.1.3
  initContainerStatuses:
  - containerID: cri-o://442e9a07adbe78d53084bbaff0317ca76a4623dc1b7df6371e2de3572ad6b2b6
    image: 10.108.30.13:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-k8s-distributed-crdloader:master
    imageID: c77fe8bd4d135f9bd4e71f50766785d3a7834713ae93242e455aea48f3c7b246
    lastState: {}
    name: contrail-k8s-crdloader
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://442e9a07adbe78d53084bbaff0317ca76a4623dc1b7df6371e2de3572ad6b2b6
        exitCode: 0
        finishedAt: "2024-01-11T12:07:44Z"
        reason: Completed
        startedAt: "2024-01-11T12:07:42Z"
  phase: Running
  podIP: 192.168.1.3
  podIPs:
  - ip: 192.168.1.3
  qosClass: BestEffort
  startTime: "2024-01-11T12:07:38Z"
