apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-01-11T12:07:38Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: webhook-service
  namespace: contrail-deploy
  uid: ba1991d7-4de6-4a40-ac78-26887c75f780
spec:
  clusterIP: 10.10.10.159
  clusterIPs:
  - 10.10.10.159
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 29443
  selector:
    app: contrail-k8s-deployer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
