apiVersion: v1
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYVcvRXYzMG9YNEF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBeE1URXhNVFUxTkRSYUZ3MHpOREF4TURneE1qQXdORFJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNwdGMrRUJvZHJRN1lnb05oK1ZGOVJBLzZMK1BUNFM5Q0R5OWRFTHpRNnBIL3dLN2prUzhrNk5rdmcKMlU0ZTZOK01PQzhpSnZzZHN5Ykl1Qm91NWN1ekRXeVhRZm5EdDgxNU9FTDlEWUtuUHo0QmQ2M0xNTEkvYTUxcgo4RTVaOU11eVNNelNTeHFqSHcwNXNZQWdFUFVKUENibUN0VlYvTGxPVmZEeEhmYjh6Wkowa2ZJam9WZlJod3Q3CjZjM2ZQTzNWTVZIdjFTRW9VTWxOQkQveWY4TGxSY3B4NEgyOWZ1aFA2MktqUEdYUUQzdWZYSWJWTTVkNjZxMS8KTEdOekhMeEdNclNRK2Z3Q0hkcW50aytlQ2hiK0dnVnFTMGg2OVQrbU52dHl1akMyOEs4YTFlV2s4MDF5UDFYagpzcmZ3WlpqbnRxUnZpVVBFdnozTU1NUUVZdFViQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSVGNBRmdxcDZKdXo0NFFzSUZCdzYzTjJjYmJUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTJmVEZOdUJ5bAo0alUrMWV3MTRkTU9LNzJCc2FPTWp2bnRraGxlcmJyNXRnTTlDaUpVRnV1TjdGY3YybFBTYy9YcUpvU2FvQTcwCmtRYkY2cXlyalU0QlpVYUlBNmRSR0FURzdCNXVzOEJ1enNmWGt1RW82NWZ0c3JkWXArbnFIMGdMa3ZXWmN4VXUKaHhQZHVMOXpheEtOODNteWRMZi9uUlREMU1WRFIyTXBsellaV0t6N1ZxTW5GY1VlRTBwZWM2Z2o5V2Q0RUpFcApLTlBGNlp6UDdSUHBwbnJiWHlxb29SYmpDZEk4NkFJMVRnbHZnNVRHYWs5Tmp4SEFDNVFHckFVV3pULzdTR1E5CnlKWkVIR203enRLK0V1MHh1WUFFTHR3OTc4Z1dNdXUwWitjcjdKWE9McEFGUSt0V2xZdGExVDZlZjZQNkpjMksKSWZhc3I5VGM5U05CCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://192.168.1.2:6443
      name: ""
    contexts: null
    current-context: ""
    kind: Config
    preferences: {}
    users: null
kind: ConfigMap
metadata:
  creationTimestamp: "2024-01-11T12:00:52Z"
  name: cluster-info
  namespace: kube-public
  uid: 2ec4f04c-c899-4c41-9ad9-5cd8c322181d
