apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-15T18:12:06Z"
involvedObject:
  apiVersion: v1
  kind: Pod
  name: coredns-756994469c-pxnkd
  namespace: kube-system
  resourceVersion: "2471225"
  uid: a5fa52ee-7a54-432c-9a48-cc69eda3eee5
kind: Event
lastTimestamp: "2024-01-15T18:12:06Z"
message: Add eth0 [10.244.35.139/32] from k8s-pod-network
metadata:
  creationTimestamp: "2024-01-15T18:12:06Z"
  name: coredns-756994469c-pxnkd.17aa97cf902a8104
  namespace: kube-system
  uid: cfd0b229-bed8-470c-86d5-2176594b7298
reason: AddedInterface
reportingComponent: ""
reportingInstance: ""
source:
  component: multus
type: Normal
