apiVersion: events.k8s.io/v1
deprecatedCount: 4666
deprecatedFirstTimestamp: "2024-01-11T12:05:56Z"
deprecatedLastTimestamp: "2024-01-15T14:02:12Z"
deprecatedSource:
  component: kubelet
  host: trohit-k8s-dpdk-kubelet1-1k3tt0.englab.juniper.net
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-11T12:05:57Z"
  name: kube-proxy-j25fx.17a9498202ed5705
  namespace: kube-system
  uid: 68695289-cbfa-4bd7-9a47-18b311116e80
note: 'Nameserver limits were exceeded, some nameservers have been omitted, the applied
  nameserver line is: 10.84.5.101 172.21.200.60 66.129.233.81'
reason: DNSConfigForming
regarding:
  apiVersion: v1
  kind: Pod
  name: kube-proxy-j25fx
  namespace: kube-system
  resourceVersion: "840"
  uid: 0c6bf464-b0a0-48d8-9a3b-a0beea94b97a
reportingController: kubelet
reportingInstance: trohit-k8s-dpdk-kubelet1-1k3tt0.englab.juniper.net
type: Warning
