apiVersion: v1
count: 1195
eventTime: null
firstTimestamp: "2024-01-15T12:35:16Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{coredns}
  kind: Pod
  name: coredns-56bc94896d-x2hjk
  namespace: kube-system
  resourceVersion: "2441391"
  uid: 28ca6708-9e7b-4f85-9965-e5e789012dbd
kind: Event
lastTimestamp: "2024-01-15T18:10:11Z"
message: 'Readiness probe failed: Get "http://10.244.35.138:8181/ready": context deadline
  exceeded (Client.Timeout exceeded while awaiting headers)'
metadata:
  creationTimestamp: "2024-01-15T12:35:16Z"
  name: coredns-56bc94896d-x2hjk.17aa856dfcb72232
  namespace: kube-system
  uid: 2575f57c-878f-420f-8987-92f4184225ff
reason: Unhealthy
reportingComponent: kubelet
reportingInstance: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
source:
  component: kubelet
  host: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
type: Warning
