apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-15T18:12:06Z"
involvedObject:
  apiVersion: apps/v1
  kind: Deployment
  name: coredns
  namespace: kube-system
  resourceVersion: "2471206"
  uid: c4c2d2a3-928e-4b23-bb8a-abdb3a78d8fc
kind: Event
lastTimestamp: "2024-01-15T18:12:06Z"
message: Scaled up replica set coredns-756994469c to 1
metadata:
  creationTimestamp: "2024-01-15T18:12:06Z"
  name: coredns.17aa97cf714d3ba5
  namespace: kube-system
  uid: 30be53d9-d545-4336-a68e-0fe1568d5074
reason: ScalingReplicaSet
reportingComponent: deployment-controller
reportingInstance: ""
source:
  component: deployment-controller
type: Normal
