apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2024-01-11T12:00:53Z"
  name: kube-controller-manager
  namespace: kube-system
  uid: b61bdd98-e35e-46a6-9b17-e10f03c2f84c
spec:
  acquireTime: "2024-01-11T12:00:53.864778Z"
  holderIdentity: trohit-k8s-master-1k3tt0.englab.juniper.net_c9a46abc-a759-4afa-9fc3-981c3210731d
  leaseDurationSeconds: 15
  leaseTransitions: 0
  renewTime: "2024-01-15T13:31:48.977786Z"
