apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 2b52b2496d5e07bdab7cc655b04f23a437971bf356c86222f724ccfb0ad41e9c
    cni.projectcalico.org/podIP: 10.244.26.65/32
    cni.projectcalico.org/podIPs: 10.244.26.65/32
  creationTimestamp: "2024-01-11T12:06:17Z"
  generateName: calico-kube-controllers-86f8947565-
  labels:
    k8s-app: calico-kube-controllers
    pod-template-hash: 86f8947565
  name: calico-kube-controllers-86f8947565-h8b5k
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: calico-kube-controllers-86f8947565
    uid: a1d8c215-7235-437f-850c-973b07a4a130
  uid: 3ef738d7-b42f-439a-a47e-be07e45dfe92
spec:
  containers:
  - env:
    - name: ENABLED_CONTROLLERS
      value: node
    - name: DATASTORE_TYPE
      value: kubernetes
    image: registry.englab.juniper.net/docker-remote/calico/kube-controllers:v3.24.5
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /usr/bin/check-status
        - -l
      failureThreshold: 6
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    name: calico-kube-controllers
    readinessProbe:
      exec:
        command:
        - /usr/bin/check-status
        - -r
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7pnbx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: trohit-k8s-dpdk-kubelet1-1k3tt0.englab.juniper.net
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: calico-kube-controllers
  serviceAccountName: calico-kube-controllers
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-7pnbx
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:06:17Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:06:36Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:06:36Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:06:17Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://515063317c4126095922c507faf04aa00e21fffd6003ccb6e0da8f1c7c1c75ce
    image: registry.englab.juniper.net/docker-remote/calico/kube-controllers:v3.24.5
    imageID: 38b76de417d5d464051916048bc6b4dbbda02c31530f7757c2e31d01bcc9aecb
    lastState: {}
    name: calico-kube-controllers
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-11T12:06:36Z"
  hostIP: 192.168.1.3
  phase: Running
  podIP: 10.244.26.65
  podIPs:
  - ip: 10.244.26.65
  qosClass: BestEffort
  startTime: "2024-01-11T12:06:17Z"
