apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: "2024-01-11T12:06:13Z"
  labels:
    k8s-app: calico-kube-controllers
  name: calico-kube-controllers
  namespace: kube-system
  uid: 37fd55b6-6ab2-4bfc-989a-00672e30afe8
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: calico-kube-controllers
status:
  conditions:
  - lastTransitionTime: "2024-01-11T12:06:36Z"
    message: ""
    observedGeneration: 1
    reason: SufficientPods
    status: "True"
    type: DisruptionAllowed
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
