apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2024-01-11T12:00:51Z"
  name: kubeadm:kubelet-config
  namespace: kube-system
  uid: 85d70ea4-6a79-46cf-bb40-a98653421871
rules:
- apiGroups:
  - ""
  resourceNames:
  - kubelet-config
  resources:
  - configmaps
  verbs:
  - get
