apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2024-01-11T12:00:51Z"
  name: kubeadm:nodes-kubeadm-config
  namespace: kube-system
  uid: 2167970c-3636-4e7c-824d-a36e12654434
rules:
- apiGroups:
  - ""
  resourceNames:
  - kubeadm-config
  resources:
  - configmaps
  verbs:
  - get
