apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2024-01-15T10:09:15Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: "true"
  name: v1.gateway.cerebrum.juniper.net
  uid: 0325af5b-d651-4fc6-975b-159852b03363
spec:
  group: gateway.cerebrum.juniper.net
  groupPriorityMinimum: 1000
  version: v1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2024-01-15T10:09:15Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
