apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2024-01-11T12:00:50Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1.
  uid: 0e9a0a06-1ece-43d0-ae2f-2c1ca69dc42a
spec:
  groupPriorityMinimum: 18000
  version: v1
  versionPriority: 1
status:
  conditions:
  - lastTransitionTime: "2024-01-11T12:00:50Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
