apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2024-01-15T10:09:15Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: "true"
  name: v1.security.cerebrum.juniper.net
  uid: e1e45b0c-42a1-44d8-bb99-3736c65abe53
spec:
  group: security.cerebrum.juniper.net
  groupPriorityMinimum: 1000
  version: v1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2024-01-15T10:09:15Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
