apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2024-01-11T12:07:44Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: "true"
  name: v1.configplane.juniper.net
  uid: 4def1356-fc53-47d5-b293-fd871215421c
spec:
  group: configplane.juniper.net
  groupPriorityMinimum: 1000
  version: v1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2024-01-11T12:07:44Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
