apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2024-01-11T12:07:44Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: "true"
  name: v1alpha1.configplane.juniper.net
  uid: d2a11227-0988-407e-b4f9-5612d16592db
spec:
  group: configplane.juniper.net
  groupPriorityMinimum: 1000
  version: v1alpha1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2024-01-11T12:07:44Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
