apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2024-01-11T12:00:50Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1.storage.k8s.io
  uid: d87b7d7f-f3b0-4474-9b37-cfbab5dddc23
spec:
  group: storage.k8s.io
  groupPriorityMinimum: 16800
  version: v1
  versionPriority: 15
status:
  conditions:
  - lastTransitionTime: "2024-01-11T12:00:50Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
