apiVersion: crd.projectcalico.org/v1
kind: BlockAffinity
metadata:
  annotations:
    projectcalico.org/metadata: '{"creationTimestamp":null}'
  creationTimestamp: "2024-01-11T12:06:31Z"
  name: trohit-k8s-dpdk-kubelet1-1k3tt0.englab.juniper.net-10-244-26-64-26
  uid: a1ab5ead-c570-470b-9fa4-65fe832833ad
spec:
  cidr: 10.244.26.64/26
  deleted: "false"
  node: trohit-k8s-dpdk-kubelet1-1k3tt0.englab.juniper.net
  state: confirmed
