apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2024-01-11T12:00:52Z"
  name: kubeadm:get-nodes
  uid: b8db9e81-f959-4021-af15-a87214074358
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
