apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2024-01-11T12:00:51Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:ephemeral-volume-controller
  uid: 8251c042-3498-4e96-8b94-f3e76ecb325b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:ephemeral-volume-controller
subjects:
- kind: ServiceAccount
  name: ephemeral-volume-controller
  namespace: kube-system
