apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-01-11T12:07:38Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: contrail-system-rolebinding
  uid: b9c6289e-c182-42d5-9f2d-db618849deaa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contrail-system-role
subjects:
- kind: ServiceAccount
  name: contrail-system-serviceaccount
  namespace: contrail-system
