apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-01-11T12:07:38Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: contrail-system-role
  uid: 0d5e0117-7a16-4908-8945-23faad9319fe
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
