apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2024-01-11T12:00:51Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:root-ca-cert-publisher
  uid: 1992d231-82ea-42e9-9868-2dc4ca8b5b8f
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - update
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
