apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "10"
  creationTimestamp: "2024-01-11T12:07:38Z"
  labels:
    jcnr: "true"
  name: ops-rolebinding
  uid: dbc1beb2-3265-4375-9339-2fc8f5f05c25
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ops-role
subjects:
- kind: ServiceAccount
  name: ops-serviceaccount
  namespace: jcnr
