apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"example-webhook"},"rules":[{"apiGroups":["core.cerebrum.juniper.net","*"],"resources":["evpns","pods"],"verbs":["get","watch","list","create","update","delete"]}]}
  creationTimestamp: "2024-01-15T11:09:51Z"
  name: example-webhook
  uid: 52df47eb-8d06-4e3c-8fcb-e7bd9ea9acf8
rules:
- apiGroups:
  - core.cerebrum.juniper.net
  - '*'
  resources:
  - evpns
  - pods
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - delete
