apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2024-01-11T12:00:51Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:kube-aggregator
  uid: 09bdbe81-26db-4016-bb84-24789513399d
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - get
  - list
  - watch
