apiVersion: crd.projectcalico.org/v1
kind: IPAMBlock
metadata:
  annotations:
    projectcalico.org/metadata: '{"creationTimestamp":null}'
  creationTimestamp: "2024-01-11T12:06:31Z"
  name: 10-244-26-64-26
  uid: 86194000-ae31-4d59-9fd4-057eff871ba7
spec:
  affinity: host:trohit-k8s-dpdk-kubelet1-1k3tt0.englab.juniper.net
  allocations:
  - 0
  - 1
  - 2
  - null
  - null
  - 3
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  attributes:
  - handle_id: ipip-tunnel-addr-trohit-k8s-dpdk-kubelet1-1k3tt0.englab.juniper.net
    secondary:
      node: trohit-k8s-dpdk-kubelet1-1k3tt0.englab.juniper.net
      type: ipipTunnelAddress
  - handle_id: k8s-pod-network.2b52b2496d5e07bdab7cc655b04f23a437971bf356c86222f724ccfb0ad41e9c
    secondary:
      namespace: kube-system
      node: trohit-k8s-dpdk-kubelet1-1k3tt0.englab.juniper.net
      pod: calico-kube-controllers-86f8947565-h8b5k
      timestamp: 2024-01-11 12:06:32.483846087 +0000 UTC
  - handle_id: k8s-pod-network.3847c805a099500cf9ba1840ca6a6ee56dac180334f1116842aeda6afbd4d8d9
    secondary:
      namespace: default
      node: trohit-k8s-dpdk-kubelet1-1k3tt0.englab.juniper.net
      pod: netshoot-pod
      timestamp: 2024-01-11 12:24:16.632743188 +0000 UTC
  - handle_id: k8s-pod-network.66e1db63885e492a8f0f45c766d4a9901b4741527857d1f3d3d7289227c25bf4
    secondary:
      namespace: kube-system
      node: trohit-k8s-dpdk-kubelet1-1k3tt0.englab.juniper.net
      pod: coredns-756994469c-zgtbh
      timestamp: 2024-01-12 10:12:44.157944309 +0000 UTC
  cidr: 10.244.26.64/26
  deleted: false
  sequenceNumber: 1704974791785807954
  sequenceNumberForAllocation:
    "0": 1704974791785807944
    "1": 1704974791785807945
    "2": 1704974791785807946
    "3": 1704974791785807947
    "4": 1704974791785807948
    "5": 1704974791785807950
    "6": 1704974791785807952
  strictAffinity: false
  unallocated:
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
  - 48
  - 49
  - 50
  - 51
  - 52
  - 53
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59
  - 60
  - 61
  - 62
  - 63
  - 4
  - 3
  - 6
