apiVersion: crd.projectcalico.org/v1
kind: KubeControllersConfiguration
metadata:
  annotations:
    projectcalico.org/metadata: '{"uid":"05ffec12-3cd7-4c1c-8d8b-66cd7c85914d","creationTimestamp":"2024-01-11T12:06:36Z"}'
  creationTimestamp: "2024-01-11T12:06:36Z"
  name: default
  uid: 05ffec12-3cd7-4c1c-8d8b-66cd7c85914d
spec:
  controllers:
    namespace:
      reconcilerPeriod: 5m0s
    node:
      leakGracePeriod: 15m0s
      reconcilerPeriod: 5m0s
      syncLabels: Enabled
    policy:
      reconcilerPeriod: 5m0s
    serviceAccount:
      reconcilerPeriod: 5m0s
    workloadEndpoint:
      reconcilerPeriod: 5m0s
  etcdV3CompactionPeriod: 10m0s
  healthChecks: Enabled
  logSeverityScreen: Info
  prometheusMetricsPort: 9094
status:
  environmentVars:
    DATASTORE_TYPE: kubernetes
    ENABLED_CONTROLLERS: node
  runningConfig:
    controllers:
      node:
        hostEndpoint:
          autoCreate: Disabled
        leakGracePeriod: 15m0s
        syncLabels: Disabled
    etcdV3CompactionPeriod: 10m0s
    healthChecks: Enabled
    logSeverityScreen: Info
