apiVersion: v1
kind: Namespace
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-01-11T12:07:38Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    kubernetes.io/metadata.name: contrail-system
  name: contrail-system
  uid: 4f825bbc-2533-41b5-b0a4-80489dcd1f0f
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
