apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2024-01-11T12:00:50Z"
  labels:
    kubernetes.io/metadata.name: kube-node-lease
  name: kube-node-lease
  uid: 8b503688-22e2-4c6f-bb1e-0077a25a4437
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
