apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-01-11T12:07:38Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    app.kubernetes.io/managed-by: Helm
  name: jcnr-pv-volume-0
  uid: 004fd992-2c45-49d7-803f-b3be340a83aa
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 256Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: conf-kube-crpd-worker-sts-0
    namespace: jcnr
    resourceVersion: "1363"
    uid: 34b24b53-dcb6-4696-a616-1fef8739a86d
  hostPath:
    path: /etc/crpd
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jcnrstorage
  volumeMode: Filesystem
status:
  phase: Bound
