apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"katafygio-pv"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"10Gi"},"hostPath":{"path":"/katafygio/data"}}}
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-01-16T05:19:30Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: katafygio-pv
  uid: eed21255-04eb-4131-af23-806c8e65ab95
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: katafygio
    namespace: default
    resourceVersion: "2529942"
    uid: 672e1953-9e60-4a99-ab55-92d72ed0a049
  hostPath:
    path: /katafygio/data
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
