apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"katafygio-pv"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"10Gi"},"hostPath":{"path":"/katafygio/data"}}}
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-01-15T13:19:21Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: katafygio-pv
  uid: c3798a33-cd0d-437c-b78d-bbc331433066
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: katafygio
    namespace: default
    resourceVersion: "516110"
    uid: fbc81461-e27b-4a77-a30a-5840a8be7ac6
  hostPath:
    path: /katafygio/data
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
