apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"katafygio-pv"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"10Gi"},"hostPath":{"path":"/katafygio/data"}}}
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-01-10T07:14:08Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: katafygio-pv
  uid: 40d948af-ba54-4e1a-b13c-20831aef73f6
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: katafygio
    namespace: default
    resourceVersion: "1777246"
    uid: 09bd7396-3885-4dd4-baaf-c67f2ed41ec7
  hostPath:
    path: /katafygio/data
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
