apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-01-11T12:07:38Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    app.kubernetes.io/managed-by: Helm
  name: jcnr-pv-volume-2
  uid: d48a60ac-adfb-4574-be2b-57aae2409ee6
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 256Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: conf-kube-crpd-worker-sts-1
    namespace: jcnr
    resourceVersion: "1373"
    uid: 7347600a-82a4-49f2-979d-f909eb82938c
  hostPath:
    path: /etc/crpd
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jcnrstorage
  volumeMode: Filesystem
status:
  phase: Bound
