apiVersion: flowcontrol.apiserver.k8s.io/v1beta2
kind: PriorityLevelConfiguration
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2024-01-11T12:00:50Z"
  name: workload-high
  uid: c76a9743-f272-46f9-a878-ae0778887810
spec:
  limited:
    assuredConcurrencyShares: 40
    lendablePercent: 50
    limitResponse:
      queuing:
        handSize: 6
        queueLengthLimit: 50
        queues: 128
      type: Queue
  type: Limited
status: {}
