apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-01-15T11:10:02Z"
  creationTimestamp: "2024-01-15T11:09:59Z"
  name: example-webhook
  namespace: default
  uid: 22037592-7010-4feb-8d62-366a0d66e662
subsets:
- addresses:
  - ip: 10.244.47.7
    nodeName: trohit-k8s-master-1k3tt0.englab.juniper.net
    targetRef:
      kind: Pod
      name: example-webhook-66f6b79986-4b878
      namespace: default
      uid: 14ff3a74-0122-49e4-a7b7-76e9abb4d32f
  ports:
  - name: application
    port: 8443
    protocol: TCP
  - name: metrics
    port: 80
    protocol: TCP
