apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2024-01-11T12:00:51Z"
  labels:
    endpointslice.kubernetes.io/skip-mirror: "true"
  name: kubernetes
  namespace: default
  uid: ab60ef59-7ba9-4cd1-9211-28f0df8f678a
subsets:
- addresses:
  - ip: 192.168.1.2
  ports:
  - name: https
    port: 6443
    protocol: TCP
