apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-16T05:19:40Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{katafygio}
  kind: Pod
  name: katafygio-767758478c-8hmsh
  namespace: default
  resourceVersion: "2529956"
  uid: 2a81751e-3d3d-444a-8658-00bba5e05cdf
kind: Event
lastTimestamp: "2024-01-16T05:19:40Z"
message: Pulling image "svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/katafygio:h2"
metadata:
  creationTimestamp: "2024-01-16T05:19:40Z"
  name: katafygio-767758478c-8hmsh.17aabc3d47089cf8
  namespace: default
  uid: 8d3460c9-1da2-4b29-ba19-9439a8b2ec5b
reason: Pulling
reportingComponent: kubelet
reportingInstance: sharmag-k8s-master-pnad30.englab.juniper.net
source:
  component: kubelet
  host: sharmag-k8s-master-pnad30.englab.juniper.net
type: Normal
