apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-16T05:14:49Z"
deprecatedLastTimestamp: "2024-01-16T05:14:49Z"
deprecatedSource:
  component: deployment-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-16T05:14:49Z"
  name: katafygio.17aabbf99dfa037c
  namespace: default
  uid: c81cb647-e38e-40a6-88c6-d83ecae10f84
note: Scaled up replica set katafygio-58fd68cf9c to 1
reason: ScalingReplicaSet
regarding:
  apiVersion: apps/v1
  kind: Deployment
  name: katafygio
  namespace: default
  resourceVersion: "2529468"
  uid: a6dca3dc-9b39-434b-929a-7b5f7eed0774
reportingController: deployment-controller
type: Normal
