apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-16T05:14:50Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{katafygio}
  kind: Pod
  name: katafygio-58fd68cf9c-bts4d
  namespace: default
  resourceVersion: "2529475"
  uid: 796a3b82-f577-4b5a-a6e0-7034a0544e5b
kind: Event
lastTimestamp: "2024-01-16T05:14:50Z"
message: Pulling image "svl-artifactory.juniper.net/atom-docker/cn2/trohit7/katafygio:includekind15"
metadata:
  creationTimestamp: "2024-01-16T05:14:50Z"
  name: katafygio-58fd68cf9c-bts4d.17aabbf9c9d588c8
  namespace: default
  uid: ccedaad0-ae5c-4ec6-99bb-7e18755ff700
reason: Pulling
reportingComponent: kubelet
reportingInstance: sharmag-k8s-master-pnad30.englab.juniper.net
source:
  component: kubelet
  host: sharmag-k8s-master-pnad30.englab.juniper.net
type: Normal
