apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-16T05:19:40Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{katafygio}
  kind: Pod
  name: katafygio-767758478c-8hmsh
  namespace: default
  resourceVersion: "2529956"
  uid: 2a81751e-3d3d-444a-8658-00bba5e05cdf
kind: Event
lastTimestamp: "2024-01-16T05:19:40Z"
message: Successfully pulled image "svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/katafygio:h2"
  in 55ms (55ms including waiting)
metadata:
  creationTimestamp: "2024-01-16T05:19:40Z"
  name: katafygio-767758478c-8hmsh.17aabc3d4a5b4f0b
  namespace: default
  uid: 80ad4ed5-aaee-4bc2-a0da-636cafd2214d
reason: Pulled
reportingComponent: kubelet
reportingInstance: sharmag-k8s-master-pnad30.englab.juniper.net
source:
  component: kubelet
  host: sharmag-k8s-master-pnad30.englab.juniper.net
type: Normal
