apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-15T12:40:00Z"
deprecatedLastTimestamp: "2024-01-15T12:40:00Z"
deprecatedSource:
  component: multus
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-15T12:40:00Z"
  name: katafygio-8f9f6bfd5-w8hqp.17aa85b0265b3cf6
  namespace: default
  uid: ce8044cc-5cd8-4112-ad4b-dd079216a91f
note: Add eth0 [10.244.47.13/32] from k8s-pod-network
reason: AddedInterface
regarding:
  apiVersion: v1
  kind: Pod
  name: katafygio-8f9f6bfd5-w8hqp
  namespace: default
  resourceVersion: "512592"
  uid: 10b6bf53-5305-45d5-9b08-837f04ebbef2
type: Normal
