action: Binding
apiVersion: events.k8s.io/v1
deprecatedFirstTimestamp: null
deprecatedLastTimestamp: null
deprecatedSource: {}
eventTime: "2024-01-16T05:14:49.697121Z"
kind: Event
metadata:
  creationTimestamp: "2024-01-16T05:14:49Z"
  name: katafygio-58fd68cf9c-bts4d.17aabbf99eb5fab6
  namespace: default
  uid: d50c44d9-df48-49fb-9cdc-c5237e75f7c4
note: Successfully assigned default/katafygio-58fd68cf9c-bts4d to sharmag-k8s-master-pnad30.englab.juniper.net
reason: Scheduled
regarding:
  apiVersion: v1
  kind: Pod
  name: katafygio-58fd68cf9c-bts4d
  namespace: default
  resourceVersion: "2529471"
  uid: 796a3b82-f577-4b5a-a6e0-7034a0544e5b
reportingController: default-scheduler
reportingInstance: default-scheduler-sharmag-k8s-master-pnad30.englab.juniper.net
type: Normal
