apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-16T05:14:50Z"
deprecatedLastTimestamp: "2024-01-16T05:14:50Z"
deprecatedSource:
  component: multus
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-16T05:14:50Z"
  name: katafygio-58fd68cf9c-bts4d.17aabbf9c7341e51
  namespace: default
  uid: 1dbaacf3-4187-4b30-97a4-d3a2dd76cb54
note: Add eth0 [10.244.100.205/32] from k8s-pod-network
reason: AddedInterface
regarding:
  apiVersion: v1
  kind: Pod
  name: katafygio-58fd68cf9c-bts4d
  namespace: default
  resourceVersion: "2529481"
  uid: 796a3b82-f577-4b5a-a6e0-7034a0544e5b
type: Normal
