apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-16T05:17:55Z"
deprecatedLastTimestamp: "2024-01-16T05:17:55Z"
deprecatedSource:
  component: kubelet
  host: sharmag-k8s-master-pnad30.englab.juniper.net
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-16T05:17:55Z"
  name: katafygio-58fd68cf9c-bts4d.17aabc24dd8fbe84
  namespace: default
  uid: 4331aebc-c63e-4425-9c17-1ec1ddd65f47
note: Stopping container katafygio
reason: Killing
regarding:
  apiVersion: v1
  fieldPath: spec.containers{katafygio}
  kind: Pod
  name: katafygio-58fd68cf9c-bts4d
  namespace: default
  resourceVersion: "2529475"
  uid: 796a3b82-f577-4b5a-a6e0-7034a0544e5b
reportingController: kubelet
reportingInstance: sharmag-k8s-master-pnad30.englab.juniper.net
type: Normal
