apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-16T05:14:49Z"
involvedObject:
  apiVersion: apps/v1
  kind: ReplicaSet
  name: katafygio-58fd68cf9c
  namespace: default
  resourceVersion: "2529469"
  uid: c502692f-e06f-4cee-b27a-b341fe17774f
kind: Event
lastTimestamp: "2024-01-16T05:14:49Z"
message: 'Created pod: katafygio-58fd68cf9c-bts4d'
metadata:
  creationTimestamp: "2024-01-16T05:14:49Z"
  name: katafygio-58fd68cf9c.17aabbf99e48982b
  namespace: default
  uid: ad6705e9-d6ba-434d-8f0b-43eb00f6511b
reason: SuccessfulCreate
reportingComponent: replicaset-controller
reportingInstance: ""
source:
  component: replicaset-controller
type: Normal
