apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-16T05:14:51Z"
deprecatedLastTimestamp: "2024-01-16T05:14:51Z"
deprecatedSource:
  component: kubelet
  host: sharmag-k8s-master-pnad30.englab.juniper.net
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-16T05:14:51Z"
  name: katafygio-58fd68cf9c-bts4d.17aabbf9ff325daf
  namespace: default
  uid: 14c963cf-f3d5-46f9-9f44-8a17f0a0f90b
note: Created container katafygio
reason: Created
regarding:
  apiVersion: v1
  fieldPath: spec.containers{katafygio}
  kind: Pod
  name: katafygio-58fd68cf9c-bts4d
  namespace: default
  resourceVersion: "2529475"
  uid: 796a3b82-f577-4b5a-a6e0-7034a0544e5b
reportingController: kubelet
reportingInstance: sharmag-k8s-master-pnad30.englab.juniper.net
type: Normal
