apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-15T13:19:32Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{katafygio}
  kind: Pod
  name: katafygio-58f79bcd55-t48hg
  namespace: default
  resourceVersion: "516125"
  uid: 8b049811-c8c3-400b-b61d-803d4738113d
kind: Event
lastTimestamp: "2024-01-15T13:19:32Z"
message: Created container katafygio
metadata:
  creationTimestamp: "2024-01-15T13:19:32Z"
  name: katafygio-58f79bcd55-t48hg.17aa87d86744b08d
  namespace: default
  uid: f19792c3-42cc-4d4b-99eb-bdbab787c795
reason: Created
reportingComponent: kubelet
reportingInstance: trohit-k8s-master-1k3tt0.englab.juniper.net
source:
  component: kubelet
  host: trohit-k8s-master-1k3tt0.englab.juniper.net
type: Normal
