apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"example-webhook","namespace":"default"}}
  creationTimestamp: "2024-01-15T11:09:51Z"
  name: example-webhook
  namespace: default
  uid: 0940021c-fa0b-4292-bcec-3263dbb7f67e
