apiVersion: v1
data:
  networkConfig: |
    controlDataNetworks:
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-01-11T12:07:38Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: contrail-network-config
  namespace: contrail
  uid: 66e45c5d-0a77-4806-834b-120303e1bf2c
