apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8070"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  creationTimestamp: "2024-01-11T12:07:46Z"
  generateName: contrail-vrouter-masters-
  labels:
    app: contrail-vrouter-masters
    controller-revision-hash: 6fc8d6dd5f
    pod-template-generation: "1"
  name: contrail-vrouter-masters-qphgg
  namespace: contrail
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: contrail-vrouter-masters
    uid: 8e548ba3-6c99-4a37-bc9a-565be45850f3
  uid: 3aa0241f-7358-4b18-965b-b6a3f9cf62c8
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - trohit-k8s-master-1k3tt0.englab.juniper.net
  containers:
  - command:
    - /vrouter-supervisor
    env:
    - name: PODIP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: PODNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: GATEWAY
    - name: AGENTMODETYPE
      value: dpdk
    - name: DATACONTROLINTERFACE
      value: enp3s0
    image: 10.108.30.13:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-agent:master
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        host: 127.0.0.1
        path: /vrouter-health-check
        port: 9091
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 5
    name: contrail-vrouter-agent
    resources: {}
    securityContext:
      capabilities:
        add:
        - SYS_MODULE
        - NET_ADMIN
        - SYS_PTRACE
      privileged: true
      runAsUser: 0
    startupProbe:
      failureThreshold: 3
      httpGet:
        host: 127.0.0.1
        path: /vrouter-health-check
        port: 9091
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/podinfo
      name: podinfo
    - mountPath: /var/lib/contrail
      name: var-lib-contrail
    - mountPath: /var/run
      name: var-run
    - mountPath: /var/run/contrail
      name: var-run-contrail
    - mountPath: /etc/contrail
      name: config-volume
    - mountPath: /var/crash
      name: var-crashes
    - mountPath: /var/log/contrail
      name: var-log-contrail
    - mountPath: /lib/modules
      name: lib-modules
    - mountPath: /dev
      name: dev
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5hwvs
      readOnly: true
  - command:
    - /dpdk-supervisor
    env:
    - name: INTERFACE_LAYER
      value: l3
    - name: RESTORE_INTERFACES
      value: "false"
    - name: PODNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    envFrom:
    - configMapRef:
        name: contrail-vrouter-masters-env-configmap
    image: 10.108.30.13:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-dpdk:master
    imagePullPolicy: IfNotPresent
    name: contrail-vrouter-agent-dpdk
    resources:
      limits:
        hugepages-1Gi: 6Gi
        memory: 6Gi
      requests:
        hugepages-1Gi: 6Gi
        memory: 6Gi
    securityContext:
      capabilities:
        add:
        - SYS_MODULE
        - NET_ADMIN
        - SYS_PTRACE
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev
      name: dev
    - mountPath: /var/lib/kubelet
      name: var-lib-kubelet
    - mountPath: /var/lib/contrail
      name: var-lib-contrail
    - mountPath: /dev/hugepages
      name: hugepages
    - mountPath: /var/run
      name: docker-unix-socket
    - mountPath: /etc/sysconfig/network-scripts
      name: network-scripts
    - mountPath: /host/bin
      name: host-bin
    - mountPath: /var/log/contrail
      name: var-log-contrail
    - mountPath: /usr/src
      name: usr-src
    - mountPath: /lib/modules
      name: lib-modules
    - mountPath: /var/crash
      name: var-crashes
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5hwvs
      readOnly: true
  - command:
    - /telemetry-exporter
    - run
    - -c
    - /etc/telemetry-exporter/config/config-vrouter.yaml
    env:
    - name: TELEMETRY_EXPORTER_SCHEME
      value: http
    - name: INTROSPECT_SCHEME
      value: http
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: TYPE
      value: vrouter
    - name: NAMESPACE
      value: contrail
    - name: INTROSPECT_SCHEME
      value: http
    image: 10.108.30.13:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-telemetry-exporter:master
    imagePullPolicy: IfNotPresent
    name: contrail-vrouter-telemetry-exporter
    ports:
    - containerPort: 8070
      hostPort: 8070
      name: metrics
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /testing
      name: telemetry-exporter-overrides
    - mountPath: /etc/config/metrics-collector
      name: metrics-collector
    - mountPath: /etc/contrail
      name: config-volume
    - mountPath: /etc/config/metrics/tls
      name: telemetry-exporter-tls
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5hwvs
      readOnly: true
  dnsPolicy: ClusterFirstWithHostNet
  enableServiceLinks: true
  hostNetwork: true
  initContainers:
  - args:
    - sysctl -w net.ipv6.conf.default.addr_gen_mode=0 && sysctl -w net.ipv6.conf.all.addr_gen_mode=0
      && sysctl -w net.ipv6.conf.default.autoconf=0 && sysctl -w net.ipv6.conf.all.autoconf=0
      && echo -e "\nSuccessfully loaded kernel parameter using sysctl cli\n" || echo
      -e "\nError in loading kernel parameter using sysctl cli\n"; modprobe tun &&
      modprobe ipip && modprobe ip_tunnel && modprobe ip6_tunnel && modprobe mpls_gso
      && modprobe mpls_router && modprobe mpls_iptunnel && modprobe vrf && modprobe
      vxlan && modprobe fou && modprobe fou6 && echo -e "\nSuccessfully loaded kernel
      modules\n" || echo -e "Error in loadinfg kernel modules. Check whether kernel
      modules packages are installed or not.\nIf running OS is Ubuntu, Run following
      command and reboot  to enable kernel modules.\nsudo apt install linux-generic
      -y \n sudo apt install --reinstall linux-image-$(uname -r) -y; \n sudo apt install
      --reinstall linux-modules-$(uname -r) -y;\n sudo apt install --reinstall linux-modules-extra-$(uname
      -r) -y; \n" ; set -o pipefail && python3 -u crpdconfig_generator/crpdconfig_generator.py
      evpn | tee -a "/var/log/contrail/cleanup.log";
    command:
    - /bin/sh
    - -c
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: PYTHONUNBUFFERED
      value: "1"
    image: svl-artifactory.juniper.net/junos-docker-local/warthog/amd64/crpdconfig-generator:v21
    imagePullPolicy: IfNotPresent
    name: jcnr-evpn-conf
    resources: {}
    securityContext:
      capabilities:
        add:
        - SYS_MODULE
        - NET_ADMIN
        - SYS_PTRACE
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/podinfo
      name: podinfo
    - mountPath: /var/lib/contrail
      name: var-lib-contrail
    - mountPath: /var/run
      name: var-run
    - mountPath: /var/run/contrail
      name: var-run-contrail
    - mountPath: /etc/contrail
      name: config-volume
    - mountPath: /var/crash
      name: var-crashes
    - mountPath: /var/log/contrail
      name: var-log-contrail
    - mountPath: /lib/modules
      name: lib-modules
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5hwvs
      readOnly: true
  - command:
    - /contrail-init
    - -service
    - vrouter
    env:
    - name: PODIP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: PODNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: NAMESPACE
      value: contrail
    - name: DATACONTROLINTERFACE
      value: enp3s0
    image: 10.108.30.13:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-init:master
    imagePullPolicy: IfNotPresent
    name: contrail-init
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/podinfo
      name: podinfo
    - mountPath: /etc/contrail
      name: config-volume
    - mountPath: /var/run
      name: var-run
    - mountPath: /var/log/contrail
      name: var-log-contrail
    - mountPath: /etc/contrail/dynamic-config
      name: dynamic-config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5hwvs
      readOnly: true
  - command:
    - /vrouter-go
    - /vrouter-go
    env:
    - name: PODNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    envFrom:
    - configMapRef:
        name: contrail-vrouter-masters-env-configmap
    image: 10.108.30.13:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-kernel-init-dpdk:master
    imagePullPolicy: IfNotPresent
    name: contrail-vrouter-kernel-init-dpdk
    resources: {}
    securityContext:
      capabilities:
        add:
        - SYS_MODULE
        - NET_ADMIN
        - SYS_PTRACE
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /usr/src
      name: usr-src
    - mountPath: /lib/modules
      name: lib-modules
    - mountPath: /etc/sysconfig/network-scripts
      name: network-scripts
    - mountPath: /host/bin
      name: host-bin
    - mountPath: /var/run
      name: docker-unix-socket
    - mountPath: /host/etc/contrail
      name: etc-contrail
    - mountPath: /var/log/contrail
      name: var-log-contrail
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5hwvs
      readOnly: true
  nodeName: trohit-k8s-master-1k3tt0.englab.juniper.net
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 2000
    runAsGroup: 3000
    runAsUser: 1000
  serviceAccount: contrail-serviceaccount
  serviceAccountName: contrail-serviceaccount
  shareProcessNamespace: true
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels
        path: lables
    name: podinfo
  - emptyDir: {}
    name: config-volume
  - configMap:
      defaultMode: 420
      name: dynamic-config-configmap
    name: dynamic-config-volume
  - configMap:
      defaultMode: 420
      name: contrail-vrouter-masters-cni-configmap
    name: cni-config-volume
  - hostPath:
      path: /var/lib/kubelet
      type: ""
    name: var-lib-kubelet
  - hostPath:
      path: /var/lib/contrail
      type: ""
    name: var-lib-contrail
  - hostPath:
      path: /var/run/contrail
      type: ""
    name: var-run-contrail
  - hostPath:
      path: /var/crash
      type: ""
    name: var-crashes
  - hostPath:
      path: /opt/cni/bin
      type: ""
    name: main-cni-bin
  - hostPath:
      path: /etc/cni/net.d
      type: ""
    name: main-cni-conf
  - hostPath:
      path: /var/run
      type: ""
    name: var-run
  - hostPath:
      path: /var/log/jcnr/
      type: DirectoryOrCreate
    name: var-log-contrail
  - hostPath:
      path: /lib/modules
      type: ""
    name: lib-modules
  - hostPath:
      path: /sys
      type: ""
    name: sys
  - hostPath:
      path: /etc
      type: ""
    name: etc
  - configMap:
      defaultMode: 420
      name: telemetry-exporter-overrides-configmap
      optional: true
    name: telemetry-exporter-overrides
  - configMap:
      defaultMode: 420
      name: metrics-collector-configmap
      optional: true
    name: metrics-collector
  - name: telemetry-exporter-tls
    secret:
      defaultMode: 420
      optional: true
      secretName: telemetry-exporter-tls
  - hostPath:
      path: /dev
      type: ""
    name: dev
  - hostPath:
      path: /etc/contrail
      type: ""
    name: etc-contrail
  - hostPath:
      path: /var/run
      type: ""
    name: docker-unix-socket
  - hostPath:
      path: /usr/src
      type: ""
    name: usr-src
  - hostPath:
      path: /dev/hugepages
      type: ""
    name: hugepages
  - hostPath:
      path: /etc/sysconfig/network-scripts
      type: ""
    name: network-scripts
  - hostPath:
      path: /bin
      type: ""
    name: host-bin
  - name: kube-api-access-5hwvs
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:07:53Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:08:28Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:08:28Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-11T12:07:46Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://87b37b0df9a502abd3691dc14cc203b3c29a829e443fa0dd961564974db1e7e9
    image: 10.108.30.13:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-agent:master
    imageID: 661ed0c78d84df091c389d05143f942e97dae6e3356edd05e40b03fab7aa20a1
    lastState: {}
    name: contrail-vrouter-agent
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-11T12:08:01Z"
  - containerID: cri-o://6553b862489d6458b83482c616a533902600057f5214a2ed68d55797b0232903
    image: 10.108.30.13:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-dpdk:master
    imageID: 42feb51f0d2efc8c8012609aea27e3118610d6be857d2349221abd8ec8c385e8
    lastState: {}
    name: contrail-vrouter-agent-dpdk
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-11T12:08:13Z"
  - containerID: cri-o://822863c0a4422fbb5f19985865ad969c31fab78fa29f36f1f4e6c56cefd3a9d4
    image: 10.108.30.13:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-telemetry-exporter:master
    imageID: 4f93c0954d18da04c11dd5700666ce2a49613190d8449e4dcefa5f781c2437b4
    lastState: {}
    name: contrail-vrouter-telemetry-exporter
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-11T12:08:14Z"
  hostIP: 192.168.1.2
  initContainerStatuses:
  - containerID: cri-o://cfc91afc7fde82c3fb17075fd3093262f4171bd6e55a3cfd0271c0216de34815
    image: svl-artifactory.juniper.net/junos-docker-local/warthog/amd64/crpdconfig-generator:v21
    imageID: b0804dda66d833cb2e4b2847807b0ccb1ec1f87c467c20e9779bbc3f088c493b
    lastState: {}
    name: jcnr-evpn-conf
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://cfc91afc7fde82c3fb17075fd3093262f4171bd6e55a3cfd0271c0216de34815
        exitCode: 0
        finishedAt: "2024-01-11T12:07:48Z"
        reason: Completed
        startedAt: "2024-01-11T12:07:47Z"
  - containerID: cri-o://91a2fd13b8921d39e8aac0764642d70e34ce00521152b5240ab798d7f299f19c
    image: 10.108.30.13:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-init:master
    imageID: 49450685d2a0932e087af198c83c9258cc2ce6a25080755ba173bf16be3020d2
    lastState: {}
    name: contrail-init
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://91a2fd13b8921d39e8aac0764642d70e34ce00521152b5240ab798d7f299f19c
        exitCode: 0
        finishedAt: "2024-01-11T12:07:51Z"
        reason: Completed
        startedAt: "2024-01-11T12:07:51Z"
  - containerID: cri-o://4ae4f58b887738955ebace6ed8eb3e190694c8a4e2e6f1ffaece8807c7953d7b
    image: 10.108.30.13:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-kernel-init-dpdk:master
    imageID: c49718217e31eaa7361a1f4253aa5c98b5df08796a7b86c4e0b83af659c1117a
    lastState: {}
    name: contrail-vrouter-kernel-init-dpdk
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://4ae4f58b887738955ebace6ed8eb3e190694c8a4e2e6f1ffaece8807c7953d7b
        exitCode: 0
        finishedAt: "2024-01-11T12:07:53Z"
        reason: Completed
        startedAt: "2024-01-11T12:07:53Z"
  phase: Running
  podIP: 192.168.1.2
  podIPs:
  - ip: 192.168.1.2
  qosClass: Burstable
  startTime: "2024-01-11T12:07:46Z"
