apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-01-11T12:07:38Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: contrail-serviceaccount
  namespace: contrail
  uid: 6e936c42-f159-4fd1-8d69-4e5111a1d79f
